config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lenses#index"
  get "/about", to: "pages#about"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lenses, only: %i[index show] do
    resources :listings, only: %i[index]
  end
  resources :listings, only: %i[create new]

  resources :listings, only: %i[index show] do
    post "blackouts", to: "blackouts#create"
    resources :bookings, only: %i[create]
    resources :reviews, only: %i[create]
  end

  resources :bookings, only: [:update]
end

app/controllers/lenses_controller.rb
class LensesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_lens, only: :show

  def index
    if params[:query].present?
      @lenses = Lens.search_by_brand_model_or_description(params[:query]).order(:brand, :model)
    else
      @lenses = Lens.all.order(:brand, :model)
    end
  end

  def show
    @listings = @lens.listings
  end

  private

  def set_lens
    @lens = Lens.find(params[:id])
  end
end

app/views/lenses/index.html.erb
<div class="container mt-4">

  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: lenses_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by brand, model, or lens type"
        %>
      <button type="submit" name="" class="btn btn-primary d-flex align-items-center">
        <i class="fa-solid fa-magnifying-glass me-1"></i>Search
      </button>
    <% end %>
  </div>
</div>

  <h2 class="my-4">We found <strong><%= @lenses.count %></strong> lenses for you!</h2>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @lenses.each do |lens| %>
      <div class="col">
        <%= link_to lens_path(lens), class: "nested-card-link" do %>
          <div class="card h-100 border-primary border-2 rounded">
            <%= cl_image_tag(lens.photo.key, class: "card-img-top py-3", style: "height: 180px; object-fit: contain;background-color: #f8f9fa;") %>
            <div class="card-body mt-2 ms-2">
              <h5 class="card-title"><strong><%= lens.brand %></strong></h5>
              <p class="card-text"><i class="fa-solid fa-camera"></i> <strong>Model:</strong> <%= lens.model %></p>
              <p class="card-text"><i class="fa-regular fa-hand-point-right"></i><%= truncate(lens.description, length: 80, separator: ' ') %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lenses/show.html.erb
<div class="container mt-4">
  <h1 class="mb-4"><strong><i class="fa-solid fa-camera me-2"></i>About <%= @lens.model %></strong></h1>
  <h5 class="mb-1"><strong><i class="fa-solid fa-info-circle me-2"></i>Description</strong></h5>
  <p><%= @lens.description %></p>

  <hr>
  <h2 class="mt-4 mb-4"><strong><i class="fa-solid fa-list me-2"></i>Listings for: <%= @lens.model %></strong></h2>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @listings.each do |listing| %>
      <div class="col">
        <%= link_to listing_path(listing), class: "nested-card-link" do %>
        <div class="card h-100 border-primary border-2 rounded">
          <% if listing.photos.attached? %>
            <div id="carousel-<%= listing.id %>" class="carousel slide">
              <div class="carousel-inner">
                <% listing.photos.each_with_index do |photo, i| %>
                  <div class="carousel-item <%= "active" if i == 0 %>">
                    <%= cl_image_tag photo.key, class: "img-fluid rounded", style: "height: 250px; width: 400px;", crop: :fill %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= listing.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= listing.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                <% end %>
              </div>
            </div>
          <% else %>
            <%= image_tag "https://image.pollinations.ai/prompt/lens+for+camera+#{listing.lens.model.gsub(' ', '+')}", class: "img-fluid rounded", style: "max-height: 250px;" %>
          <% end %>
          <div class="card-body mt-2 ms-2">
            <h5 class="card-title"><i class="fa-solid fa-coins me-1"></i><%= listing.daily_rate %> per day</h5>
            <p class="card-text"><i class="fa-regular fa-hand-point-right me-1"></i><%= truncate(listing.owner_description, length: 80, separator: ' ') %></p>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>