config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lenses#index"
  get "/about", to: "pages#about"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lenses, only: %i[index show] do
    resources :listings, only: %i[index]
  end
  resources :listings, only: %i[create new]

  resources :listings, only: %i[index show] do
    post "blackouts", to: "blackouts#create"
    resources :bookings, only: %i[create]
    resources :reviews, only: %i[create]
  end

  resources :bookings, only: [:update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span class="brand-text">FocusHub</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to root_path, class: "nav-link" do %>
              <i class="fa-solid fa-house me-1"></i>Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do %>
              <i class="fa-solid fa-table-list me-1"></i>My Dashboard
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_listing_path, class: "nav-link" do %>
              <i class="fa-solid fa-plus me-1"></i>List your lens
            <% end %>
          </li>

          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://image.pollinations.ai/prompt/lens+for+camera+canon", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Bookings", "#", class: "dropdown-item" %>
              <%= link_to "#{current_user.user_name} Profile", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>